import pymysql
db = pymysql.connect(host='localhost', user='root', password='1991513', port=3306, db='T_STUFF')
cursor=db.cursor()
sql = """CREATE TABLE T_STUFF(

STUFFID VARCHAR(256) NOT NULL,
USERID VARCHAR(256),
ALERT VARCHAR(256),
PRICE Double,
VIEWTIMES INTEGER NULL,
DESCINFO VARCHAR(256),
IMAGEURL VARCHAR(256),
STUFFURL VARCHAR(256),
ADDRESS VARCHAR(256) NULL,
SELLERNAME VARCHAR(256),
SELLERICON VARCHAR(256),
SELLERWW VARCHAR(256) NULL,
SELLERSHOPURL VARCHAR(256),
SELLERVIP VARCHAR(256) NULL,
MSGCOUNT INTEGER,
IMAGELOCALURL VARCHAR(256) NULL,
CUST1 VARCHAR(256) NULL,
CUST2 VARCHAR(256) NULL,
CUST3 VARCHAR(256),
CUST4 VARCHAR(256) NULL,
CUST6 VARCHAR(256) NOT NULL,
CUST7 VARCHAR(256) NULL,
CUST8 VARCHAR(256) NULL,
CUST9 VARCHAR(256) NULL,
CUST10 VARCHAR(256) NULL,
CUST5 VARCHAR(256),
PRIMARY KEY(STUFFID),
CREATE_DATE VARCHAR(256) ,
UPDATE_DATE VARCHAR(256)
)"""

cursor.execute(sql)
db.close()
print('创建表成功,表名为T_STUFF')



#  sql数据库的基本操作
#  查询所有的数据库名 show databases;
#  进入某个数据库  use 数据库名
#  查看数据库里面的表名 show tables;
#  查看表中的内容 select * from 表名
#  删除一个表 DROP TABLE 表名;
