import pymysql
db = pymysql.connect(host='localhost', user='root', password='1991513', port=3306, db='JINSHILI')
cursor=db.cursor()
sql = """CREATE TABLE APPS(


URL VARCHAR(256) DEFAULT NULL,
NAME VARCHAR(256) DEFAULT NULL,
IMG VARCHAR(256) DEFAULT NULL,
SECC VARCHAR(256) DEFAULT NULL,
TITLE VARCHAR(256) DEFAULT NULL,
PRICE VARCHAR(256) DEFAULT NULL,
LIM VARCHAR(256) DEFAULT NULL,
FY VARCHAR(256) DEFAULT NULL,
METHOD VARCHAR(256) DEFAULT NULL,
DZ VARCHAR(256) DEFAULT NULL,
TIMESS VARCHAR(256) DEFAULT NULL,
CUST1 VARCHAR(256) DEFAULT NULL,
CUST2 VARCHAR(256) DEFAULT NULL,
CUST3 VARCHAR(256) DEFAULT NULL,
CUST4 VARCHAR(256) DEFAULT NULL,
CUST5 VARCHAR(256) DEFAULT NULL,
CUST6 VARCHAR(256) DEFAULT NULL,
CUST7 VARCHAR(256) DEFAULT NULL,
CUST8 VARCHAR(256) DEFAULT NULL,
CUST9 VARCHAR(256) DEFAULT NULL,
CUST10 VARCHAR(256) DEFAULT NULL,
CREATE_DATE VARCHAR(256) DEFAULT NULL,
UPDATE_DATE VARCHAR(256) DEFAULT NULL
)"""

cursor.execute(sql)
db.close()
print('创建表成功,表名为APPS')
